Condition to verify we are in a CTU-Malware-Capture-Botnet-X folder
I got a :
Current Folder: CTU-Normal-31
Traceback (most recent call last):
  File "collect_infected_ips.py", line 116, in <module>
    dataset_number = int(sub_set.split('-')[4])
IndexError: list index out of range

Thus adding a condition in the beginning